### ISSUE TITLE
WHMCS Error

### ISSUE THREAD

**Issue by TorabRamin** [jetchirag/bunnycdn-whmcs#1]
I create a new product and set custom field. after placing order I'm getting this error. Do I need to put my account API key anywhere?
![image](https://user-images.githubusercontent.com/12676522/57816090-d5ac8400-779b-11e9-81bf-86c1b2237a79.png)

**Comment by jetchirag** [comment]
https://github.com/jetchirag/bunnycdn-whmcs/commit/da6ebca779b692d23292a53528d3045abca19158

Pushed an edit. Can you confirm if it is working now?
