### ISSUE TITLE
WHMCS 8

### ISSUE THREAD

**Issue by harrisonratcliffe** [jetchirag/bunnycdn-whmcs#3]
Does this still work?

**Comment by jetchirag** [comment]
It does.

**Comment by harrisonratcliffe** [comment]
Do you have an example of the server settings you use? I’m unsure where the api code goes and what host to use.

Sent from Mail for Windows 10

**Comment by harrisonratcliffe** [comment]
Any update?

**Comment by jetchirag** [comment]
You need to create a new server and provide API key as server's password.

**Comment by harrisonratcliffe** [comment]
Thank you!
